INSERT INTO TASK (DESCRIPTION, NAME)
VALUES ('MAKE SOME WORK', 'YOU NEED DO THIS');

INSERT INTO TASK (DESCRIPTION, NAME)
VALUES ('TASK1', 'IT`S TASK #1');

INSERT INTO TASK (DESCRIPTION, NAME)
VALUES ('TASK2', 'IT`S TASK #2');