INSERT INTO TASK (NAME, DESCRIPTION, COLUMN_NAME)
VALUES ('MAKE SOME WORK', 'YOU NEED DO THIS', 'TASK');

INSERT INTO TASK (NAME, DESCRIPTION, COLUMN_NAME)
VALUES ('TASK1', 'IT`S TASK #1', 'TASK');

INSERT INTO TASK (NAME, DESCRIPTION, COLUMN_NAME)
VALUES ('TASK2', 'IT`S TASK #2', 'TASK');